### ISSUE TITLE
[rtorrent-flood] WebUI not loading properly

### ISSUE THREAD

**Issue by Diablofan** [Wonderfall/dockerfiles#135]
I just installed your rtorrent-flood container, and I'm coming across an error. I'm attempting to use it in a virtual directory `/flood`, and I'm getting errors in the terminal, `sed: bad option in substitution expression`, and then when I look at the web page for flood, I'm noticing  `window.floodConfig = {baseURI: '<CONTEXT_PATH>', maxHistoryStates: 30, pollInterval: 5000};` with a very suspicious `<CONTEXT_PATH>` where there should be a `'/flood'` isntead.

That might be because my CONTEXT_PATH is set like this: `CONTEXT_PATH=/flood`, though I changed how the value was quoted and it didn't fix it.

My guess is that the sed expression that is throwing the error is resolving to: `sed -i -e "s/<CONTEXT_PATH>//flood/g" /usr/flood/config.js` which is causing sed to feak out.

**Comment by Wonderfall** [comment]
Should be fixed in the next build.

**Comment by Diablofan** [comment]
That fixed it, still have some problems but I believe that is with my nginx config. Thanks.
