### ISSUE TITLE
[nextcloud] php memory_limit as environment variable

### ISSUE THREAD

**Issue by jazzdd86** [Wonderfall/dockerfiles#84]
As I got my solr and nextant working I stumbled over the next issue. PHPs default 128MB memory_limit are not enough memory to index all the files with nextant. So it would be great to change that with an environment variable.

**Comment by maldag** [comment]
#116 has'nt fixed this issue here I think.

**Comment by nrgeen** [comment]
That would be great!
At the moment only the cron has a variable memory_limit. For occ the common memory_limit of 128 mb is too small!! :-(

**Comment by Wonderfall** [comment]
It should be simple to do. I'll push a commit in the following hours/days. :)

**Comment by Wonderfall** [comment]
I'll push something but not until Alpine Linux fixes this shit : https://bugs.alpinelinux.org/issues/7039
It's been a few days and no answer yet. My images cannot be built anymore. 😤

**Comment by nrgeen** [comment]
This is of course very annoying!
Thanks for the update and especially for your commitment!

**Comment by Wonderfall** [comment]
I pushed a temporary fix instead...
Now you can configure PHP memory limit. ☺️

**Comment by nrgeen** [comment]
Does it work with you?

If I execute for example the command `docker exec -ti Nextcloud occ preview:generate-all` (used for Preview Generator) the following error message still appears:

> PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes) in /nextcloud/lib/private/legacy/image.php on line 450

However, in the administration area of Nextcloud the new memory limit is shown to me:
![screensh_nextcloud_php](https://cloud.githubusercontent.com/assets/7750335/24270646/5197f440-1016-11e7-8b61-d9fdaf58d28b.jpg)


The error message also affects Nextant.

Do you have an idea?

**Comment by hoellen** [comment]
PR [#159](https://github.com/Wonderfall/dockerfiles/pull/159) should fix it.
